### ISSUE TITLE
An unhandled exception of type 'System.InvalidCastException' occurred in LanguageNet.Grammarian.dll

### ISSUE THREAD

**Issue by Ahmedn1** [jrising/Virsona-ChatBot-Tools#34]
When I tried to run the "Test Paraphrasing" solution 
I had this exception in the Parse() method in GrammarParser Class 

"An unhandled exception of type 'System.InvalidCastException' occurred in LanguageNet.Grammarian.dll
Additional information: Unable to cast object of type 'LanguageNet.AgentParser.Fragment' to type 'LanguageNet.Grammarian.IParsedPhrase'."

in this line:
return (IParsedPhrase)result;

Any Solution?

**Comment by jrising** [comment]
Sorry for the long delay!  This would happen if you don't have Memcached installed, which is used to provide fast access to synonyms in WordNet.

I've added a check to the code, so it won't give you an exception, and tells you what's wrong.  Try pulling again.

It would be nice to have a fall-back option for WordNet when Memcached is not available, but I don't have it there yet.
